src/main/java/blog/data/model/Post.java
package blog.data.model;

import java.util.Date;

public class Post {

	private String id;
	private String title;
	private String subTitle;
	private String content;
	private Date dtcreated;
	private Date dtupdated;
	private String user;
	private String dateStr;
	private String status;
	
	public String getId() {
		return id;
	}
	public void setId(String id) {
		this.id = id;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
	public String getSubTitle() {
		return subTitle;
	}
	public void setSubTitle(String subTitle) {
		this.subTitle = subTitle;
	}
	public String getContent() {
		return content;
	}
	public void setContent(String content) {
		this.content = content;
	}
	public String getUser() {
		return user;
	}
	public void setUser(String user) {
		this.user = user;
	}
	public String getDateStr() {
		return dateStr;
	}
	public void setDateStr(String dateStr) {
		this.dateStr = dateStr;
	}
	public Date getDtcreated() {
		return dtcreated;
	}
	public void setDtcreated(Date dtcreated) {
		this.dtcreated = dtcreated;
	}
	public Date getDtupdated() {
		return dtupdated;
	}
	public void setDtupdated(Date dtupdated) {
		this.dtupdated = dtupdated;
	}
	public String getStatus() {
		return status;
	}
	public void setStatus(String status) {
		this.status = status;
	}
	
}

src/main/java/blog/data/model/UrlModel.java
package blog.data.model;

import javax.servlet.http.HttpServletRequest;

public class UrlModel {

	private static String scheme;
	private static String host;
	private static int port;
	private static String path;
	
	public UrlModel(HttpServletRequest request){
		UrlModel.scheme = request.getScheme();
		UrlModel.host = request.getServerName();
		UrlModel.port = request.getServerPort();
		UrlModel.path = request.getContextPath();
	}
	
	public String getScheme() {
		return scheme;
	}
	public String getHost() {
		return host;
	}
	public int getPort() {
		return port;
	}
	public String getPath() {
		return path;
	}
	public String getFull() {
		return scheme+"://"+host+":"+Integer.toString(port)+path;
	}
	public String getSiteOnly(){
		return scheme+"://"+host+":"+Integer.toString(port);
	}
	
}

src/main/java/blog/controller/LoginController.java
package blog.controller;

import java.io.IOException;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.ModelMap;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.client.HttpClientErrorException;
import org.springframework.web.servlet.ModelAndView;

import blog.data.enumeration.EnumSessionVariables;
import blog.data.model.UrlModel;
import blog.data.model.User;
import blog.service.CredentialService;
import blog.ui.model.CommonUi;
import blog.util.SessionUtil;

@Controller
public class LoginController {

	@Autowired
	private CredentialService credentialService;
	
	@RequestMapping(value = "/loginEncryptedByMyself", method = RequestMethod.GET)
	public ModelAndView login(HttpSession session, HttpServletRequest request, HttpServletResponse response) throws HttpClientErrorException, IOException {
		if (SessionUtil.isLogged(session, response)){
			UrlModel url = new UrlModel(request);
			response.setHeader("Location", url.getFull()+"/dashboard/postList");
		}
		CommonUi commonUi = new CommonUi();		
		return new ModelAndView("login", commonUi);
	}
	
	@RequestMapping(value = "/login", method = RequestMethod.POST)
	public ModelAndView loginPost(HttpSession session, @ModelAttribute("credential") User user)  {
		if (credentialService.validateLogin(user.getUsername(),user.getPassword())) {
			session.setAttribute(EnumSessionVariables.user.toString(), user.getUsername());
			return new ModelAndView("redirect:dashboard/postList");
		} else{
			return new ModelAndView("login", new CommonUi());
		}
	}

}

src/main/webapp/WEB-INF/pages/about.jsp
<!DOCTYPE html>
<html lang="en">

<body>

    <!-- Navigation -->
    <jsp:include page="header/header.jsp"/>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('resources/img/contact-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>${about.title }</h1>
                        <hr class="small">
                        <span class="subheading">${about.subTitle }</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            	${about.content}

				<!-- Facebook Like & Share -->
				<div class="fb-like"
					data-href="javascript:$(location).attr('href');"
					data-layout="standard" data-action="like" data-show-faces="false"
					data-share="true"></div>
				<!-- Disqus -->
				<div id="disqus_thread"></div>
				<script type="text/javascript">
					/* * * CONFIGURATION VARIABLES * * */
					var disqus_shortname = 'blogharunalfatcom';

					/* * * DON'T EDIT BELOW THIS LINE * * */
					(function() {
						var dsq = document.createElement('script');
						dsq.type = 'text/javascript';
						dsq.async = true;
						dsq.src = '//' + disqus_shortname
								+ '.disqus.com/embed.js';
						(document.getElementsByTagName('head')[0] || document
								.getElementsByTagName('body')[0])
								.appendChild(dsq);
					})();
				</script>
				<noscript>
					Please enable JavaScript to view the <a
						href="https://disqus.com/?ref_noscript" rel="nofollow">comments
						powered by Disqus.</a>
				</noscript>
			</div>
        </div>
    </div>

    <!-- Footer -->
    <jsp:include page="footer/footer.jsp"/>

</body>

</html>

src/main/webapp/WEB-INF/pages/contact.jsp
<!DOCTYPE html>
<html lang="en">

<body>

    <!-- Navigation -->
    <jsp:include page="header/header.jsp"/>

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('resources/img/contact-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading">
                        <h1>Contact Me</h1>
                        <hr class="small">
                        <span class="subheading">Have questions? I have answers (maybe).</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within 24 hours!</p>
                <!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
                <!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
                <!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
                <form name="sentMessage" id="contactForm" novalidate>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Name</label>
                            <input type="text" class="form-control" placeholder="Name" id="name" required data-validation-required-message="Please enter your name.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Email Address</label>
                            <input type="email" class="form-control" placeholder="Email Address" id="email" required data-validation-required-message="Please enter your email address.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Phone Number</label>
                            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required data-validation-required-message="Please enter your phone number.">
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <div class="row control-group">
                        <div class="form-group col-xs-12 floating-label-form-group controls">
                            <label>Message</label>
                            <textarea rows="5" class="form-control" placeholder="Message" id="message" required data-validation-required-message="Please enter a message."></textarea>
                            <p class="help-block text-danger"></p>
                        </div>
                    </div>
                    <br>
                    <div id="success"></div>
                    <div class="row">
                        <div class="form-group col-xs-12">
                            <button type="submit" class="btn btn-default">Send</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <jsp:include page="footer/footer.jsp"/>

</body>

</html>

src/main/webapp/WEB-INF/pages/index.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">

<body>

    <!-- Navigation -->
	<jsp:include page="header/header.jsp"/>    

    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('resources/img/home-bg.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="site-heading">
                        <h1>Kode Hidup</h1>
                        <hr class="small">
                        <span class="subheading">Kisah Sang Developer</span>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Main Content -->
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
            	<c:forEach items="${postList}" var="post" varStatus="loop">
            		<div class="post-preview">            			
            			<a href="<%=request.getContextPath()%>/post?postId=${post.title}">
            				<h2 class="post-title">
            					${post.title }
            				</h2>
            				<h3 class="post-subtitle">
            					${post.subTitle }
            				</h3>
            			</a>
            			<div class="disqus-comment-count post-meta" data-disqus-url="${url.full}/post?postId=${post.title}"></div>
            			<p class="post-meta">Posted by ${post.user } on ${post.dateStr} </p>
            			
            		</div>
            		<hr>
            	</c:forEach>
                <!-- Pager -->
                <ul class="pager">
                    <li class="next">
                        <a href="#">Older Posts &rarr;</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    
    <jsp:include page="footer/footer.jsp"/>
    <!-- Disqus Count -->
	<script type="text/javascript">
		/* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
		var disqus_shortname = 'blogharunalfatcom'; // required: replace example with your forum shortname

		/* * * DON'T EDIT BELOW THIS LINE * * */
		(function() {
			var s = document.createElement('script');
			s.async = true;
			s.type = 'text/javascript';
			s.src = '//' + disqus_shortname + '.disqus.com/count.js';
			(document.getElementsByTagName('HEAD')[0] || document
					.getElementsByTagName('BODY')[0]).appendChild(s);
		}());
	</script>

</body>

</html>

src/main/webapp/WEB-INF/pages/login.jsp
<!DOCTYPE HTML>
<html>
<head>
<title>Simple Login Form</title>
<meta charset="UTF-8" />
<meta name="Designer" content="PremiumPixels.com">
<meta name="Author" content="$hekh@r d-Ziner, CSSJUNTION.com">
<link rel="stylesheet" type="text/css" href="/resources/css/reset.css">
<link rel="stylesheet" type="text/css" href="/resources/css/structure.css">
</head>

<body>
<form class="box login" name="credential" action="login" method="post">
	<fieldset class="boxBody">
	  <label>Username</label>
	  <input type="text" name="username" tabindex="1" placeholder="Username" required>
	  <label><a href="#" class="rLink" tabindex="5">Forget your password?</a>Password</label>
	  <input type="password" name="password" tabindex="2" placeholder="Password" required>
	</fieldset>
	<footer>
	  <label><input type="checkbox" tabindex="3">Keep me logged in</label>
	  <input type="submit" class="btnLogin" value="Login" tabindex="4">
	</footer>
</form>
<footer id="main">
  <a href="http://wwww.cssjunction.com">Simple Login Form (HTML5/CSS3 Coded) by CSS Junction</a> | <a href="http://www.premiumpixels.com">PSD by Premium Pixels</a>
</footer>
</body>
</html>

src/main/webapp/WEB-INF/pages/post.jsp
<%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<!DOCTYPE html>
<html lang="en">
	
<head>
	<link href="<%=request.getContextPath()%>/resources/css/prism.css" rel="stylesheet">
</head>	

<body>
	
    <!-- Navigation -->
    <jsp:include page="header/header.jsp"/>
    <!-- Facebook JS -->
    <div id="fb-root"></div>
	<script>	
		window.fbAsyncInit = function() {
			FB.init({
				appId : '1576701875928447',
				xfbml : true,
				version : 'v2.3'
			});
		};

		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) {
				return;
			}
			js = d.createElement(s);
			js.id = id;
			js.src = "//connect.facebook.net/en_US/sdk.js";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'facebook-jssdk'));
	</script>
	
	<!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('<%=request.getContextPath()%>/resources/img/fireworks2.jpg')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="post-heading">
                        <h1>${post.title }</h1>
                        <h2 class="subheading">${post.subTitle }</h2>
                        <c:if test="${post.status == 'new' }"><span class="meta">Posted by ${post.user} on ${post.dateStr }</span></c:if>
                        <c:if test="${post.status == 'edited' }"><span class="meta">Last Edited by ${post.user} on ${post.dateStr }</span></c:if>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- Post Content -->
    <article>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">                
                	${post.content }
                	
                	<!-- Facebook Like & Share -->
					<div class="fb-like"
						data-href="${url.full}<%=request.getAttribute("javax.servlet.forward.request_uri")%>?postId=${post.id}"
						data-layout="standard" data-action="like" data-show-faces="false"
						data-share="true"></div>
					<!-- Disqus -->
					<div id="disqus_thread"></div>
					<script type="text/javascript">
						/* * * CONFIGURATION VARIABLES * * */
						var disqus_shortname = 'blogharunalfatcom';

						/* * * DON'T EDIT BELOW THIS LINE * * */
						(function() {
							var dsq = document.createElement('script');
							dsq.type = 'text/javascript';
							dsq.async = true;
							dsq.src = '//' + disqus_shortname
									+ '.disqus.com/embed.js';
							(document.getElementsByTagName('head')[0] || document
									.getElementsByTagName('body')[0])
									.appendChild(dsq);
						})();
					</script>
					<noscript>
						Please enable JavaScript to view the <a
							href="https://disqus.com/?ref_noscript" rel="nofollow">comments
							powered by Disqus.</a>
					</noscript>

				</div>
            </div>
        </div>
    </article>
    

	<!-- Footer -->
    <jsp:include page="footer/footer.jsp"/>

</body>

<script src="<%=request.getContextPath()%>/resources/js/prism.js" />
<script>
	$(document).ready(function() {
		Prism.highlightAll();
	});
</script>

</html>